### ISSUE TITLE
Wrong tag value for 19.7.41.1

### ISSUE THREAD

**Issue by Julieeeen** [ansible-lockdown/Windows-2016-CIS#14]
- name: "SCORED | 19.7.41.1 | PATCH | (L1) Ensure 'Always install with elevated privileges' is set to 'Disabled'"
  block:
    - name: "SCORED | 19.7.41.1 | PATCH | (L1) Ensure 'Always install with elevated privileges' is set to 'Disabled'"
      win_regedit:
          path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Installer
          name: AlwaysInstallElevated
          data: 0
          type: dword

    - name: "SCORED | 19.7.41.1 | PATCH | (L1) Ensure 'Always install with elevated privileges' is set to 'Disabled'"
      win_regedit:
          path: HKCU:\Software\Policies\Microsoft\Windows\Installer
          name: AlwaysInstallElevated
          data: 0
          type: dword
  when: rule_19_7_41_1
  tags:
    - **level1**
    - **level2**
    - rule_19.7.41.1
    - patch

**Comment by georgenalen** [comment]
Addressed with PR#24 and release 1.2.1
