### ISSUE TITLE
Controls 2.3.1.5 and 2.3.1.6 use hardcoded values instead of variables

### ISSUE THREAD

**Issue by bschapendonk** [ansible-lockdown/Windows-2016-CIS#16]
https://github.com/ansible-lockdown/Windows-2016-CIS/blob/devel/tasks/section02.yml#L704

https://github.com/ansible-lockdown/Windows-2016-CIS/blob/devel/tasks/section02.yml#L718

**Comment by georgenalen** [comment]
Addressed with PR#24 and release 1.2.1
