### ISSUE TITLE
Post task not executed

### ISSUE THREAD

**Issue by adsk-spm** [ansible-lockdown/Windows-2016-CIS#43]
**Describe the Issue**
Post task (reboot) is not included in main task, so it is skipped and the handler doesn't run when expected to.

**Expected Behavior**
Post task included, flush handlers executed

**Actual Behavior**
Post task skipped, handlers not executed at end of role execution.

**Control(s) Affected**
None

**Environment (please complete the following information):**

- branch being used: [e.g. devel]
- Ansible Version: [e.g. 2.10]
- Host Python Version: [e.g. Python 3.7.6]
- Ansible Server Python Version: [e.g. Python 3.7.6]
- Additional Details:

**Additional Notes**
None

**Possible Solution**
Include task post in main.yml

**Comment by frederickw082922** [comment]
resolved in #44  by @mfortin !
